### ISSUE TITLE
Fix Jute version info

### ISSUE THREAD

**Issue by fjarri** [fjarri/Jute.jl#24]
`Pkg3` doesn't seem to support getting your own version at the moment (see [this issue](https://github.com/JuliaLang/Pkg.jl/issues/385)), so currently in the logs Jute version is replaced by `<undefined>`. Need to fix when the way of getting the version is clear.

**Comment by Seanny123** [comment]
Seems resolved to me. I get a proper version number when I run `Pkg.installed()`.

**Comment by fjarri** [comment]
There were problems with getting the version this way, because at the moment the package had a `Project.toml`, and apparently in that case the version of the package itself is not included in the list. The `Pkg` issue is still open, so I guess they haven't yet decided on the proper API. But `installed()` does work for me now, so I suppose there's no harm in trying to get the version there.
